### ISSUE TITLE
[BUG] It allows to make fake transactions.

### ISSUE THREAD

**Issue by nageamol** [PatilShreyas/EasyUpiPayment-Android#39] opened 2020-09-01 08:20 UTC
Write information about Bug/Feature Request hereRs
Rs. 97,566.00 entry received with success status.

**Comment by PatilShreyas** [comment] 2020-09-02 07:37
@nageamol Can you describe what's exactly happening?

**Comment by shankar7545** [comment] 2020-09-11 07:25
@PatilShreyas  I think @nageamol want you to create a feature to generate fake transactions .

**Comment by nageamol** [comment] 2020-09-11 07:35
@shankar7545  

In existing, users is making fake transactions. i.e. Rs. 97,566.00 entry received with success status. but i did not receive any amount in bank or not found such transaction in banks statement.

**Comment by shankar7545** [comment] 2020-09-11 07:38
Ooo , that's bad.

I was thinking to use this dependency in my app.

It seems like i might wanna wait till this bug clears.

Did u find put how users managed to create fake transaction?

**Comment by PatilShreyas** [comment] 2020-09-11 08:17
@nageamol How to reproduce this?

**Comment by nageamol** [comment] 2020-09-12 05:45
Trying to reproduce from last month.

**Comment by PatilShreyas** [comment] 2020-09-12 09:58
This description is not valid then. Without proper information about bug/problem this issue will be invalid. Provide us valid information about it asap.

**Comment by pryanshuarora** [comment] 2020-10-10 14:43
@nageamol  DId you hit this issue . The project seems to be really good and I was thinking of integrating this with my App. Want to know if you have encountered any such issue again.

**Comment by nageamol** [comment] 2020-10-20 06:04
@pryanshuarora Not able to reproduce issue. same issue encounterd again and again. and the issue is only for PAYTM UPI so rest of all  is working fine. Daily transaction of my client is 1-2 lac and all are only from UPI. so we disabled PAYTM for now.

**Comment by PatilShreyas** [comment] 2020-10-20 06:26
So this issue is not associated with this library. Can we close this? @nageamol

**Comment by nageamol** [comment] 2020-10-20 06:33
@PatilShreyas This is associated with may be paytm. anyway you can close it.

**Comment by PatilShreyas** [comment] 2020-10-20 08:08
I'm closing this. Still, if you found how to reproduce it then please share with us.

**Closed by PatilShreyas** 2020-10-20 08:08 UTC
Labels: invalid
