### ISSUE TITLE
 No UPI app exists on this device to perform this transaction.

### ISSUE THREAD

**Issue by mallipurna03** [PatilShreyas/EasyUpiPayment-Android#51] opened 2020-10-02 07:51 UTC
This libray is very helpful for us to handle UPI payments with simple steps. Great work but i am facing below issue when i used this libray. Please help me to resolve this issue. Once i tap payment from the sample app and if no application available in my device getting crashed.

com.shreyaspatil.easyupipayment.exception.AppNotFoundException: No UPI app exists on this device to perform this transaction.

**Comment by goforbg** [comment] 2020-10-02 11:07
Can I take this up @PatilShreyas ?

**Comment by PatilShreyas** [comment] 2020-10-02 11:32
But what you'll do to solve this issue @goforbg?

**Comment by PatilShreyas** [comment] 2020-10-02 11:32
As the problem mentioned in this issue. This is already expected behaviour

**Comment by goforbg** [comment] 2020-10-02 11:35
@PatilShreyas I'm seeing an official list athttps://www.npci.org.in/upi-PSP%263rdpartyApps

We can maintain a list of array of packages, write a small util function see if those packages are installed using Package Manager and wrap it inside a try catch.

**Comment by PatilShreyas** [comment] 2020-10-02 11:41
@goforbg It's already implemented.

**Comment by mallipurna03** [comment] 2020-10-02 14:26
yes, even it is crashing..

**Comment by ItzNotABug** [comment] 2020-10-19 11:08
> yes, even it is crashing..

This is an expected behaviour as per the current code.

@PatilShreyas,
Maybe show an error warning in the console or maybe add one more method to the Listener when no apps are found?
Avoiding a straight-up crash can be good.

**Comment by adarsh45** [comment] 2020-10-19 11:41
I am facing a similar issue.
I have taken care of AppNotFoundException with log and a toast
But still, the app crashes when no payment app is available on the phone.
Please also guide me if I am doing something wrong while writing code.

```
EasyUpiPayment.Builder builder = null;
EasyUpiPayment easyUpiPayment = null;

try {
    builder = new EasyUpiPayment.Builder(FoldersScreen.this)
                .with(PaymentApp.ALL)
                .setPayeeVpa("upi_id@upi")
                .setPayeeName("payee_name")
                .setTransactionId(tr_td)
                .setTransactionRefId(tr_ref_id)
                .setDescription(desc)
                .setAmount(amount);
} 
catch (IllegalStateException isExc){
    Log.d(TAG, "payThroughUPI: "+ isExc.getLocalizedMessage());
    Toast.makeText(this, isExc.getLocalizedMessage(), Toast.LENGTH_SHORT).show();
} 
finally {
        try {
            easyUpiPayment = builder.build();
        } catch (AppNotFoundException e){
            Log.d(TAG, "payThroughUPI: "+ e.getLocalizedMessage());
            Toast.makeText(this, "UPI app not found", Toast.LENGTH_SHORT).show();
        } finally {
            easyUpiPayment.startPayment();
            easyUpiPayment.setPaymentStatusListener(this);
        }
}
```

**Comment by ItzNotABug** [comment] 2020-10-19 16:00
First of, there's no need to use a `try/catch` block to create the `builder` variable.
Secondly, can you share the stack-trace?

**Comment by PatilShreyas** [comment] 2020-11-03 09:53
Since this is expected and working fine, closing this

**Closed** 2020-11-03 09:53 UTC
